[app]
name = "mkube"

[app.http]
host = "127.0.0.1"
port = 8882

[app.grpc]
host = "127.0.0.1"
port = 8883

[mongodb]
username = ""
password = ""
endpoints = ["192.168.1.130:27017"]
database = "mkube"
authsource = "mkube"

[k8s]
kubeconfig = "etc/config"

[plugin]
provisionser = "cluster.local/nfs-subdir-external-provisioner"

[harbor]
scheme = "https"
username = "admin"
password = "Harbor12345"
host = "192.168.1.130"
cacerts = "etc/ca.crt"