// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: apps/metrics/pb/metrics.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricSet结构体
type MetricSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"total" json:"total"
	Total int64 `protobuf:"varint,1,opt,name=Total,proto3" json:"total" bson:"total"`
	// @gotags: bson:"items" json:"items"
	Items []*MetricItem `protobuf:"bytes,2,rep,name=Items,proto3" json:"items" bson:"items"`
}

func (x *MetricSet) Reset() {
	*x = MetricSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_metrics_pb_metrics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSet) ProtoMessage() {}

func (x *MetricSet) ProtoReflect() protoreflect.Message {
	mi := &file_apps_metrics_pb_metrics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSet.ProtoReflect.Descriptor instead.
func (*MetricSet) Descriptor() ([]byte, []int) {
	return file_apps_metrics_pb_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricSet) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MetricSet) GetItems() []*MetricItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// MetricItem结构体
type MetricItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"title" json:"title"
	Title string `protobuf:"bytes,1,opt,name=Title,proto3" json:"title" bson:"title"`
	// @gotags: bson:"label" json:"label"
	Label string `protobuf:"bytes,2,opt,name=Label,proto3" json:"label" bson:"label"`
	// @gotags: bson:"value" json:"value"
	Value string `protobuf:"bytes,3,opt,name=Value,proto3" json:"value" bson:"value"`
	// @gotags: bson:"color" json:"color"
	Color string `protobuf:"bytes,4,opt,name=Color,proto3" json:"color" bson:"color"`
	// @gotags: bson:"logo" json:"logo"
	Logo string `protobuf:"bytes,5,opt,name=Logo,proto3" json:"logo" bson:"logo"`
}

func (x *MetricItem) Reset() {
	*x = MetricItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_metrics_pb_metrics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricItem) ProtoMessage() {}

func (x *MetricItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_metrics_pb_metrics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricItem.ProtoReflect.Descriptor instead.
func (*MetricItem) Descriptor() ([]byte, []int) {
	return file_apps_metrics_pb_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MetricItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MetricItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MetricItem) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *MetricItem) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

var File_apps_metrics_pb_metrics_proto protoreflect.FileDescriptor

var file_apps_metrics_pb_metrics_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x70,
	0x62, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x2e, 0x6d, 0x6b, 0x75, 0x62, 0x65,
	0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x5c, 0x0a, 0x09, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x53, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x39, 0x0a, 0x05, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x64,
	0x65, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x2e, 0x6d, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x78, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x4c, 0x6f, 0x67, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x6f, 0x67, 0x6f,
	0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x6f, 0x6c, 0x6f, 0x64, 0x62, 0x61, 0x2f, 0x64, 0x65, 0x76, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f,
	0x6d, 0x6b, 0x75, 0x62, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_metrics_pb_metrics_proto_rawDescOnce sync.Once
	file_apps_metrics_pb_metrics_proto_rawDescData = file_apps_metrics_pb_metrics_proto_rawDesc
)

func file_apps_metrics_pb_metrics_proto_rawDescGZIP() []byte {
	file_apps_metrics_pb_metrics_proto_rawDescOnce.Do(func() {
		file_apps_metrics_pb_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_metrics_pb_metrics_proto_rawDescData)
	})
	return file_apps_metrics_pb_metrics_proto_rawDescData
}

var file_apps_metrics_pb_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apps_metrics_pb_metrics_proto_goTypes = []interface{}{
	(*MetricSet)(nil),  // 0: codehorse.mkube.metrics.MetricSet
	(*MetricItem)(nil), // 1: codehorse.mkube.metrics.MetricItem
}
var file_apps_metrics_pb_metrics_proto_depIdxs = []int32{
	1, // 0: codehorse.mkube.metrics.MetricSet.Items:type_name -> codehorse.mkube.metrics.MetricItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_metrics_pb_metrics_proto_init() }
func file_apps_metrics_pb_metrics_proto_init() {
	if File_apps_metrics_pb_metrics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_metrics_pb_metrics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_metrics_pb_metrics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_metrics_pb_metrics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_metrics_pb_metrics_proto_goTypes,
		DependencyIndexes: file_apps_metrics_pb_metrics_proto_depIdxs,
		MessageInfos:      file_apps_metrics_pb_metrics_proto_msgTypes,
	}.Build()
	File_apps_metrics_pb_metrics_proto = out.File
	file_apps_metrics_pb_metrics_proto_rawDesc = nil
	file_apps_metrics_pb_metrics_proto_goTypes = nil
	file_apps_metrics_pb_metrics_proto_depIdxs = nil
}
