// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: apps/harbor/pb/harbor.proto

package harbor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Page结构体
type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"currentPage" json:"currentPage"
	CurrentPage int64 `protobuf:"varint,1,opt,name=CurrentPage,proto3" json:"currentPage" bson:"currentPage"`
	// @gotags: bson:"pageSize" json:"pageSize"
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"pageSize" bson:"pageSize"`
	// @gotags: bson:"totalCount" json:"totalCount"
	TotalCount int64 `protobuf:"varint,3,opt,name=TotalCount,proto3" json:"totalCount" bson:"totalCount"`
	// @gotags: bson:"totalPage" json:"totalPage"
	TotalPage int64 `protobuf:"varint,4,opt,name=TotalPage,proto3" json:"totalPage" bson:"totalPage"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_harbor_pb_harbor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_apps_harbor_pb_harbor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_apps_harbor_pb_harbor_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *Page) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Page) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Page) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

// Projects结构体
type Projects struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:",inline" json:"page"
	Page *Page `protobuf:"bytes,1,opt,name=page,proto3" json:"page" bson:",inline"`
	// @gotags: bson:",inline" json:"data"
	Data []*ProjectData `protobuf:"bytes,2,rep,name=Data,proto3" json:"data" bson:",inline"`
}

func (x *Projects) Reset() {
	*x = Projects{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_harbor_pb_harbor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Projects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Projects) ProtoMessage() {}

func (x *Projects) ProtoReflect() protoreflect.Message {
	mi := &file_apps_harbor_pb_harbor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Projects.ProtoReflect.Descriptor instead.
func (*Projects) Descriptor() ([]byte, []int) {
	return file_apps_harbor_pb_harbor_proto_rawDescGZIP(), []int{1}
}

func (x *Projects) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *Projects) GetData() []*ProjectData {
	if x != nil {
		return x.Data
	}
	return nil
}

// ProjectData结构体
type ProjectData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"creation_time" json:"creation_time"
	CreationTime string `protobuf:"bytes,1,opt,name=CreationTime,proto3" json:"creation_time" bson:"creation_time"`
	// @gotags: bson:"current_user_role_id" json:"current_user_role_id"
	CurrentUserRoleID int64 `protobuf:"varint,2,opt,name=CurrentUserRoleID,proto3" json:"current_user_role_id" bson:"current_user_role_id"`
	// @gotags: bson:"current_user_role_ids" json:"current_user_role_ids"
	CurrentUserRoleIds []int64 `protobuf:"varint,3,rep,packed,name=CurrentUserRoleIds,proto3" json:"current_user_role_ids" bson:"current_user_role_ids"`
	// @gotags: bson:"cve_allowlist" json:"cve_allowlist"
	CveAllowlist *CveAllowlist `protobuf:"bytes,4,opt,name=CveAllowlist,proto3" json:"cve_allowlist" bson:"cve_allowlist"`
	// @gotags: bson:"metadata" json:"metadata"
	Metadata *Metadata `protobuf:"bytes,5,opt,name=Metadata,proto3" json:"metadata" bson:"metadata"`
	// @gotags: bson:"name" json:"name"
	Name string `protobuf:"bytes,6,opt,name=Name,proto3" json:"name" bson:"name"`
	// @gotags: bson:"owner_id" json:"owner_id"
	OwnerID int64 `protobuf:"varint,7,opt,name=OwnerID,proto3" json:"owner_id" bson:"owner_id"`
	// @gotags: bson:"owner_name" json:"owner_name"
	OwnerName string `protobuf:"bytes,8,opt,name=OwnerName,proto3" json:"owner_name" bson:"owner_name"`
	// @gotags: bson:"project_id" json:"project_id"
	ProjectID int64 `protobuf:"varint,9,opt,name=ProjectID,proto3" json:"project_id" bson:"project_id"`
	// @gotags: bson:"repo_count" json:"repo_count"
	RepoCount int64 `protobuf:"varint,10,opt,name=RepoCount,proto3" json:"repo_count" bson:"repo_count"`
	// @gotags: bson:"update_time" json:"update_time"
	UpdateTime string `protobuf:"bytes,11,opt,name=UpdateTime,proto3" json:"update_time" bson:"update_time"`
}

func (x *ProjectData) Reset() {
	*x = ProjectData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_harbor_pb_harbor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectData) ProtoMessage() {}

func (x *ProjectData) ProtoReflect() protoreflect.Message {
	mi := &file_apps_harbor_pb_harbor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectData.ProtoReflect.Descriptor instead.
func (*ProjectData) Descriptor() ([]byte, []int) {
	return file_apps_harbor_pb_harbor_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectData) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

func (x *ProjectData) GetCurrentUserRoleID() int64 {
	if x != nil {
		return x.CurrentUserRoleID
	}
	return 0
}

func (x *ProjectData) GetCurrentUserRoleIds() []int64 {
	if x != nil {
		return x.CurrentUserRoleIds
	}
	return nil
}

func (x *ProjectData) GetCveAllowlist() *CveAllowlist {
	if x != nil {
		return x.CveAllowlist
	}
	return nil
}

func (x *ProjectData) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProjectData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectData) GetOwnerID() int64 {
	if x != nil {
		return x.OwnerID
	}
	return 0
}

func (x *ProjectData) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *ProjectData) GetProjectID() int64 {
	if x != nil {
		return x.ProjectID
	}
	return 0
}

func (x *ProjectData) GetRepoCount() int64 {
	if x != nil {
		return x.RepoCount
	}
	return 0
}

func (x *ProjectData) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

// CveAllowlist结构体
type CveAllowlist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"creation_time" json:"creation_time"
	CreationTime string `protobuf:"bytes,1,opt,name=CreationTime,proto3" json:"creation_time" bson:"creation_time"`
	// @gotags: bson:"id" json:"id"
	ID int64 `protobuf:"varint,2,opt,name=ID,proto3" json:"id" bson:"id"`
	// @gotags: bson:"items" json:"items"
	Items []string `protobuf:"bytes,3,rep,name=Items,proto3" json:"items" bson:"items"`
	// @gotags: bson:"project_id" json:"project_id"
	ProjectID int64 `protobuf:"varint,4,opt,name=ProjectID,proto3" json:"project_id" bson:"project_id"`
	// @gotags: bson:"update_time" json:"update_time"
	UpdateTime string `protobuf:"bytes,5,opt,name=UpdateTime,proto3" json:"update_time" bson:"update_time"`
}

func (x *CveAllowlist) Reset() {
	*x = CveAllowlist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_harbor_pb_harbor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CveAllowlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CveAllowlist) ProtoMessage() {}

func (x *CveAllowlist) ProtoReflect() protoreflect.Message {
	mi := &file_apps_harbor_pb_harbor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CveAllowlist.ProtoReflect.Descriptor instead.
func (*CveAllowlist) Descriptor() ([]byte, []int) {
	return file_apps_harbor_pb_harbor_proto_rawDescGZIP(), []int{3}
}

func (x *CveAllowlist) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

func (x *CveAllowlist) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *CveAllowlist) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CveAllowlist) GetProjectID() int64 {
	if x != nil {
		return x.ProjectID
	}
	return 0
}

func (x *CveAllowlist) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

// Metadata结构体
type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"public" json:"public"
	Public string `protobuf:"bytes,1,opt,name=Public,proto3" json:"public" bson:"public"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_harbor_pb_harbor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_apps_harbor_pb_harbor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_apps_harbor_pb_harbor_proto_rawDescGZIP(), []int{4}
}

func (x *Metadata) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

var File_apps_harbor_pb_harbor_proto protoreflect.FileDescriptor

var file_apps_harbor_pb_harbor_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x68, 0x61, 0x72, 0x62, 0x6f, 0x72, 0x2f, 0x70, 0x62,
	0x2f, 0x68, 0x61, 0x72, 0x62, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63,
	0x6f, 0x64, 0x65, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x2e, 0x6d, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x68,
	0x61, 0x72, 0x62, 0x6f, 0x72, 0x22, 0x82, 0x01, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x22, 0x75, 0x0a, 0x08, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x6f, 0x72, 0x73, 0x65,
	0x2e, 0x6d, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x68, 0x61, 0x72, 0x62, 0x6f, 0x72, 0x2e, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x6f, 0x72,
	0x73, 0x65, 0x2e, 0x6d, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x68, 0x61, 0x72, 0x62, 0x6f, 0x72, 0x2e,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x22, 0xbf, 0x03, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x11, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x12, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x12, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x73, 0x12, 0x48, 0x0a, 0x0c, 0x43, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x64, 0x65,
	0x68, 0x6f, 0x72, 0x73, 0x65, 0x2e, 0x6d, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x68, 0x61, 0x72, 0x62,
	0x6f, 0x72, 0x2e, 0x43, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x0c, 0x43, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a,
	0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x2e, 0x6d, 0x6b, 0x75, 0x62,
	0x65, 0x2e, 0x68, 0x61, 0x72, 0x62, 0x6f, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6f, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x52, 0x65, 0x70, 0x6f, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x96, 0x01, 0x0a, 0x0c, 0x43, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x6c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x08,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x6f, 0x6c, 0x6f, 0x64, 0x62, 0x61, 0x2f, 0x64, 0x65, 0x76, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f,
	0x6d, 0x6b, 0x75, 0x62, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x68, 0x61, 0x72, 0x62, 0x6f,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_harbor_pb_harbor_proto_rawDescOnce sync.Once
	file_apps_harbor_pb_harbor_proto_rawDescData = file_apps_harbor_pb_harbor_proto_rawDesc
)

func file_apps_harbor_pb_harbor_proto_rawDescGZIP() []byte {
	file_apps_harbor_pb_harbor_proto_rawDescOnce.Do(func() {
		file_apps_harbor_pb_harbor_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_harbor_pb_harbor_proto_rawDescData)
	})
	return file_apps_harbor_pb_harbor_proto_rawDescData
}

var file_apps_harbor_pb_harbor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_apps_harbor_pb_harbor_proto_goTypes = []interface{}{
	(*Page)(nil),         // 0: codehorse.mkube.harbor.Page
	(*Projects)(nil),     // 1: codehorse.mkube.harbor.Projects
	(*ProjectData)(nil),  // 2: codehorse.mkube.harbor.ProjectData
	(*CveAllowlist)(nil), // 3: codehorse.mkube.harbor.CveAllowlist
	(*Metadata)(nil),     // 4: codehorse.mkube.harbor.Metadata
}
var file_apps_harbor_pb_harbor_proto_depIdxs = []int32{
	0, // 0: codehorse.mkube.harbor.Projects.page:type_name -> codehorse.mkube.harbor.Page
	2, // 1: codehorse.mkube.harbor.Projects.Data:type_name -> codehorse.mkube.harbor.ProjectData
	3, // 2: codehorse.mkube.harbor.ProjectData.CveAllowlist:type_name -> codehorse.mkube.harbor.CveAllowlist
	4, // 3: codehorse.mkube.harbor.ProjectData.Metadata:type_name -> codehorse.mkube.harbor.Metadata
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_apps_harbor_pb_harbor_proto_init() }
func file_apps_harbor_pb_harbor_proto_init() {
	if File_apps_harbor_pb_harbor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_harbor_pb_harbor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_harbor_pb_harbor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Projects); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_harbor_pb_harbor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_harbor_pb_harbor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CveAllowlist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_harbor_pb_harbor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_harbor_pb_harbor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_harbor_pb_harbor_proto_goTypes,
		DependencyIndexes: file_apps_harbor_pb_harbor_proto_depIdxs,
		MessageInfos:      file_apps_harbor_pb_harbor_proto_msgTypes,
	}.Build()
	File_apps_harbor_pb_harbor_proto = out.File
	file_apps_harbor_pb_harbor_proto_rawDesc = nil
	file_apps_harbor_pb_harbor_proto_goTypes = nil
	file_apps_harbor_pb_harbor_proto_depIdxs = nil
}
