[app]
name = "mcenter"

[app.http]
host = "127.0.0.1"
port = 8888

[app.grpc]
host = "127.0.0.1"
port = 8889

[mongodb]
username = ""
password = ""
endpoints = ["175.27.242.200:27017"]
database = "mcenter"
authsource = "mcenter"
