[app]
name = "mpaas"

[app.http]
host = "127.0.0.1"
port = 8882

[app.grpc]
host = "127.0.0.1"
port = 8883

[mongodb]
username = ""
password = ""
endpoints = ["146.56.241.184:27017"]
database = "mpaas"
authsource = "mpaas"

[k8s]
kubeconfig = "etc/config"
