// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: apps/namespace/pb/namespace.proto

package namespace

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Namespace集合结构体
type NamespaceSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"total" json:"total"
	Total int64 `protobuf:"varint,1,opt,name=Total,proto3" json:"total" bson:"total"`
	// @gotags: bson:"items" json:"items"
	Items []*NamespaceSetItem `protobuf:"bytes,2,rep,name=Items,proto3" json:"items" bson:"items"`
}

func (x *NamespaceSet) Reset() {
	*x = NamespaceSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_namespace_pb_namespace_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespaceSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceSet) ProtoMessage() {}

func (x *NamespaceSet) ProtoReflect() protoreflect.Message {
	mi := &file_apps_namespace_pb_namespace_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceSet.ProtoReflect.Descriptor instead.
func (*NamespaceSet) Descriptor() ([]byte, []int) {
	return file_apps_namespace_pb_namespace_proto_rawDescGZIP(), []int{0}
}

func (x *NamespaceSet) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *NamespaceSet) GetItems() []*NamespaceSetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// NamespaceSetItem结构体
type NamespaceSetItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"name" json:"name"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"name" bson:"name"`
	// @gotags: bson:"creationTimestamp" json:"creationTimestamp"
	CreationTimestamp int64 `protobuf:"varint,2,opt,name=CreationTimestamp,proto3" json:"creationTimestamp" bson:"creationTimestamp"`
	// @gotags: bson:"status" json:"status"
	Status string `protobuf:"bytes,3,opt,name=Status,proto3" json:"status" bson:"status"`
}

func (x *NamespaceSetItem) Reset() {
	*x = NamespaceSetItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_namespace_pb_namespace_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespaceSetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceSetItem) ProtoMessage() {}

func (x *NamespaceSetItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_namespace_pb_namespace_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceSetItem.ProtoReflect.Descriptor instead.
func (*NamespaceSetItem) Descriptor() ([]byte, []int) {
	return file_apps_namespace_pb_namespace_proto_rawDescGZIP(), []int{1}
}

func (x *NamespaceSetItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamespaceSetItem) GetCreationTimestamp() int64 {
	if x != nil {
		return x.CreationTimestamp
	}
	return 0
}

func (x *NamespaceSetItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_apps_namespace_pb_namespace_proto protoreflect.FileDescriptor

var file_apps_namespace_pb_namespace_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x2f, 0x70, 0x62, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x19, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x2e, 0x6d,
	0x70, 0x61, 0x61, 0x73, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x67,
	0x0a, 0x0c, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x41, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x2e,
	0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x6c, 0x0a, 0x10, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x2c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x64, 0x62, 0x61, 0x2f, 0x64, 0x65, 0x76, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_apps_namespace_pb_namespace_proto_rawDescOnce sync.Once
	file_apps_namespace_pb_namespace_proto_rawDescData = file_apps_namespace_pb_namespace_proto_rawDesc
)

func file_apps_namespace_pb_namespace_proto_rawDescGZIP() []byte {
	file_apps_namespace_pb_namespace_proto_rawDescOnce.Do(func() {
		file_apps_namespace_pb_namespace_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_namespace_pb_namespace_proto_rawDescData)
	})
	return file_apps_namespace_pb_namespace_proto_rawDescData
}

var file_apps_namespace_pb_namespace_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apps_namespace_pb_namespace_proto_goTypes = []interface{}{
	(*NamespaceSet)(nil),     // 0: codehorse.mpaas.namespace.NamespaceSet
	(*NamespaceSetItem)(nil), // 1: codehorse.mpaas.namespace.NamespaceSetItem
}
var file_apps_namespace_pb_namespace_proto_depIdxs = []int32{
	1, // 0: codehorse.mpaas.namespace.NamespaceSet.Items:type_name -> codehorse.mpaas.namespace.NamespaceSetItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_namespace_pb_namespace_proto_init() }
func file_apps_namespace_pb_namespace_proto_init() {
	if File_apps_namespace_pb_namespace_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_namespace_pb_namespace_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamespaceSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_namespace_pb_namespace_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamespaceSetItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_namespace_pb_namespace_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_namespace_pb_namespace_proto_goTypes,
		DependencyIndexes: file_apps_namespace_pb_namespace_proto_depIdxs,
		MessageInfos:      file_apps_namespace_pb_namespace_proto_msgTypes,
	}.Build()
	File_apps_namespace_pb_namespace_proto = out.File
	file_apps_namespace_pb_namespace_proto_rawDesc = nil
	file_apps_namespace_pb_namespace_proto_goTypes = nil
	file_apps_namespace_pb_namespace_proto_depIdxs = nil
}
