[app]
name = "maudit"

[app.http]
host = "127.0.0.1"
port = 8886

[app.grpc]
host = "127.0.0.1"
port = 8887

[mongodb]
username = ""
password = ""
endpoints = ["192.168.1.130:27017"]
database = "maudit"
authsource = "maudit"

[kafka]
endpoints = ["192.168.1.130:9092"]
username = ""
password = ""
topic = "audit_log"
consumer_group = "audit_log_controller"