// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: apps/pvc/pb/pvc.proto

package pvc

import (
	meta "github.com/solodba/mcube/pb/meta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreatePVCRequest结构体
type CreatePVCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"name" json:"name"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"name" bson:"name"`
	// @gotags: bson:"namespace" json:"namespace"
	Namespace string `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"namespace" bson:"namespace"`
	// @gotags: bson:"labels" json:"labels"
	Labels []*ListMapItem `protobuf:"bytes,3,rep,name=Labels,proto3" json:"labels" bson:"labels"`
	// @gotags: bson:"accessModes" json:"accessModes"
	AccessModes []string `protobuf:"bytes,4,rep,name=AccessModes,proto3" json:"accessModes" bson:"accessModes"`
	// @gotags: bson:"capacity" json:"capacity"
	Capacity int32 `protobuf:"varint,5,opt,name=Capacity,proto3" json:"capacity" bson:"capacity"`
	// @gotags: bson:"selector" json:"selector"
	Selector []*ListMapItem `protobuf:"bytes,6,rep,name=Selector,proto3" json:"selector" bson:"selector"`
	// @gotags: bson:"storageClassName" json:"storageClassName"
	StorageClassName string `protobuf:"bytes,7,opt,name=StorageClassName,proto3" json:"storageClassName" bson:"storageClassName"`
}

func (x *CreatePVCRequest) Reset() {
	*x = CreatePVCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_pvc_pb_pvc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePVCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePVCRequest) ProtoMessage() {}

func (x *CreatePVCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pvc_pb_pvc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePVCRequest.ProtoReflect.Descriptor instead.
func (*CreatePVCRequest) Descriptor() ([]byte, []int) {
	return file_apps_pvc_pb_pvc_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePVCRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePVCRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreatePVCRequest) GetLabels() []*ListMapItem {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreatePVCRequest) GetAccessModes() []string {
	if x != nil {
		return x.AccessModes
	}
	return nil
}

func (x *CreatePVCRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreatePVCRequest) GetSelector() []*ListMapItem {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *CreatePVCRequest) GetStorageClassName() string {
	if x != nil {
		return x.StorageClassName
	}
	return ""
}

// 通用键值对结构体
type ListMapItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"key" json:"key"
	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"key" bson:"key"`
	// @gotags: bson:"value" json:"value"
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"value" bson:"value"`
}

func (x *ListMapItem) Reset() {
	*x = ListMapItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_pvc_pb_pvc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMapItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMapItem) ProtoMessage() {}

func (x *ListMapItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pvc_pb_pvc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMapItem.ProtoReflect.Descriptor instead.
func (*ListMapItem) Descriptor() ([]byte, []int) {
	return file_apps_pvc_pb_pvc_proto_rawDescGZIP(), []int{1}
}

func (x *ListMapItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListMapItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// PVC结构体
type PVC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:",inline" json:"meta"
	Meta *meta.Meta `protobuf:"bytes,1,opt,name=Meta,proto3" json:"meta" bson:",inline"`
	// @gotags: bson:",inline" json:"pvc"
	PVC *CreatePVCRequest `protobuf:"bytes,2,opt,name=PVC,proto3" json:"pvc" bson:",inline"`
}

func (x *PVC) Reset() {
	*x = PVC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_pvc_pb_pvc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVC) ProtoMessage() {}

func (x *PVC) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pvc_pb_pvc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVC.ProtoReflect.Descriptor instead.
func (*PVC) Descriptor() ([]byte, []int) {
	return file_apps_pvc_pb_pvc_proto_rawDescGZIP(), []int{2}
}

func (x *PVC) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PVC) GetPVC() *CreatePVCRequest {
	if x != nil {
		return x.PVC
	}
	return nil
}

// PVCSetItem结构体
type PVCSetItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"name" json:"name"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"name" bson:"name"`
	// @gotags: bson:"namespace" json:"namespace"
	Namespace string `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"namespace" bson:"namespace"`
	// @gotags: bson:"labels" json:"labels"
	Labels []*ListMapItem `protobuf:"bytes,3,rep,name=Labels,proto3" json:"labels" bson:"labels"`
	// @gotags: bson:"accessModes" json:"accessModes"
	AccessModes []string `protobuf:"bytes,4,rep,name=AccessModes,proto3" json:"accessModes" bson:"accessModes"`
	// @gotags: bson:"capacity" json:"capacity"
	Capacity int32 `protobuf:"varint,5,opt,name=Capacity,proto3" json:"capacity" bson:"capacity"`
	// @gotags: bson:"selector" json:"selector"
	Selector []*ListMapItem `protobuf:"bytes,6,rep,name=Selector,proto3" json:"selector" bson:"selector"`
	// @gotags: bson:"storageClassName" json:"storageClassName"
	StorageClassName string `protobuf:"bytes,7,opt,name=StorageClassName,proto3" json:"storageClassName" bson:"storageClassName"`
	// @gotags: bson:"age" json:"age"
	Age int64 `protobuf:"varint,8,opt,name=Age,proto3" json:"age" bson:"age"`
	// @gotags: bson:"status" json:"status"
	Status string `protobuf:"bytes,9,opt,name=Status,proto3" json:"status" bson:"status"`
	// @gotags: bson:"volume" json:"volume"
	Volume string `protobuf:"bytes,10,opt,name=Volume,proto3" json:"volume" bson:"volume"`
}

func (x *PVCSetItem) Reset() {
	*x = PVCSetItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_pvc_pb_pvc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVCSetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVCSetItem) ProtoMessage() {}

func (x *PVCSetItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pvc_pb_pvc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVCSetItem.ProtoReflect.Descriptor instead.
func (*PVCSetItem) Descriptor() ([]byte, []int) {
	return file_apps_pvc_pb_pvc_proto_rawDescGZIP(), []int{3}
}

func (x *PVCSetItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PVCSetItem) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PVCSetItem) GetLabels() []*ListMapItem {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PVCSetItem) GetAccessModes() []string {
	if x != nil {
		return x.AccessModes
	}
	return nil
}

func (x *PVCSetItem) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *PVCSetItem) GetSelector() []*ListMapItem {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *PVCSetItem) GetStorageClassName() string {
	if x != nil {
		return x.StorageClassName
	}
	return ""
}

func (x *PVCSetItem) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PVCSetItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PVCSetItem) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

// PVCSet结构体
type PVCSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"total" json:"total"
	Total int64 `protobuf:"varint,1,opt,name=Total,proto3" json:"total" bson:"total"`
	// @gotags: bson:"items" json:"items"
	Items []*PVCSetItem `protobuf:"bytes,2,rep,name=Items,proto3" json:"items" bson:"items"`
}

func (x *PVCSet) Reset() {
	*x = PVCSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_pvc_pb_pvc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVCSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVCSet) ProtoMessage() {}

func (x *PVCSet) ProtoReflect() protoreflect.Message {
	mi := &file_apps_pvc_pb_pvc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVCSet.ProtoReflect.Descriptor instead.
func (*PVCSet) Descriptor() ([]byte, []int) {
	return file_apps_pvc_pb_pvc_proto_rawDescGZIP(), []int{4}
}

func (x *PVCSet) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PVCSet) GetItems() []*PVCSetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_apps_pvc_pb_pvc_proto protoreflect.FileDescriptor

var file_apps_pvc_pb_pvc_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70, 0x76, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x76,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x6f, 0x72,
	0x73, 0x65, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x70, 0x76, 0x63, 0x1a, 0x35, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x64, 0x62, 0x61, 0x2f, 0x6d, 0x63, 0x75, 0x62, 0x65,
	0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x02, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x56,
	0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x64,
	0x65, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x70, 0x76, 0x63,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x6f,
	0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x4d, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69,
	0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69,
	0x74, 0x79, 0x12, 0x3c, 0x0a, 0x08, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x6f, 0x72, 0x73, 0x65,
	0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x70, 0x76, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x61, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x2a, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x0b,
	0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x6e, 0x0a, 0x03, 0x50, 0x56, 0x43, 0x12, 0x2e, 0x0a, 0x04, 0x4d, 0x65,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x68,
	0x6f, 0x72, 0x73, 0x65, 0x2e, 0x6d, 0x63, 0x75, 0x62, 0x65, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x03, 0x50, 0x56,
	0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x6f,
	0x72, 0x73, 0x65, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x70, 0x76, 0x63, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x56, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03,
	0x50, 0x56, 0x43, 0x22, 0xe2, 0x02, 0x0a, 0x0a, 0x50, 0x56, 0x43, 0x53, 0x65, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x6f, 0x72, 0x73, 0x65,
	0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x70, 0x76, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x61, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x20,
	0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x3c, 0x0a, 0x08,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73,
	0x2e, 0x70, 0x76, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x08, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x41, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x22, 0x55, 0x0a, 0x06, 0x50, 0x56, 0x43, 0x53,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x35, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x68, 0x6f,
	0x72, 0x73, 0x65, 0x2e, 0x6d, 0x70, 0x61, 0x61, 0x73, 0x2e, 0x70, 0x76, 0x63, 0x2e, 0x50, 0x56,
	0x43, 0x53, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x42,
	0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f,
	0x6c, 0x6f, 0x64, 0x62, 0x61, 0x2f, 0x64, 0x65, 0x76, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x6d,
	0x70, 0x61, 0x61, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70, 0x76, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_pvc_pb_pvc_proto_rawDescOnce sync.Once
	file_apps_pvc_pb_pvc_proto_rawDescData = file_apps_pvc_pb_pvc_proto_rawDesc
)

func file_apps_pvc_pb_pvc_proto_rawDescGZIP() []byte {
	file_apps_pvc_pb_pvc_proto_rawDescOnce.Do(func() {
		file_apps_pvc_pb_pvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_pvc_pb_pvc_proto_rawDescData)
	})
	return file_apps_pvc_pb_pvc_proto_rawDescData
}

var file_apps_pvc_pb_pvc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_apps_pvc_pb_pvc_proto_goTypes = []interface{}{
	(*CreatePVCRequest)(nil), // 0: codehorse.mpaas.pvc.CreatePVCRequest
	(*ListMapItem)(nil),      // 1: codehorse.mpaas.pvc.ListMapItem
	(*PVC)(nil),              // 2: codehorse.mpaas.pvc.PVC
	(*PVCSetItem)(nil),       // 3: codehorse.mpaas.pvc.PVCSetItem
	(*PVCSet)(nil),           // 4: codehorse.mpaas.pvc.PVCSet
	(*meta.Meta)(nil),        // 5: codehorse.mcube.meta.Meta
}
var file_apps_pvc_pb_pvc_proto_depIdxs = []int32{
	1, // 0: codehorse.mpaas.pvc.CreatePVCRequest.Labels:type_name -> codehorse.mpaas.pvc.ListMapItem
	1, // 1: codehorse.mpaas.pvc.CreatePVCRequest.Selector:type_name -> codehorse.mpaas.pvc.ListMapItem
	5, // 2: codehorse.mpaas.pvc.PVC.Meta:type_name -> codehorse.mcube.meta.Meta
	0, // 3: codehorse.mpaas.pvc.PVC.PVC:type_name -> codehorse.mpaas.pvc.CreatePVCRequest
	1, // 4: codehorse.mpaas.pvc.PVCSetItem.Labels:type_name -> codehorse.mpaas.pvc.ListMapItem
	1, // 5: codehorse.mpaas.pvc.PVCSetItem.Selector:type_name -> codehorse.mpaas.pvc.ListMapItem
	3, // 6: codehorse.mpaas.pvc.PVCSet.Items:type_name -> codehorse.mpaas.pvc.PVCSetItem
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_apps_pvc_pb_pvc_proto_init() }
func file_apps_pvc_pb_pvc_proto_init() {
	if File_apps_pvc_pb_pvc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_pvc_pb_pvc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePVCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_pvc_pb_pvc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMapItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_pvc_pb_pvc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_pvc_pb_pvc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVCSetItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_pvc_pb_pvc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVCSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_pvc_pb_pvc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_pvc_pb_pvc_proto_goTypes,
		DependencyIndexes: file_apps_pvc_pb_pvc_proto_depIdxs,
		MessageInfos:      file_apps_pvc_pb_pvc_proto_msgTypes,
	}.Build()
	File_apps_pvc_pb_pvc_proto = out.File
	file_apps_pvc_pb_pvc_proto_rawDesc = nil
	file_apps_pvc_pb_pvc_proto_goTypes = nil
	file_apps_pvc_pb_pvc_proto_depIdxs = nil
}
